/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.shaxowskiy.javaspeakerclub.jooq.tables.Lectures;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LecturesRecord extends UpdatableRecordImpl<LecturesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>lectures.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>lectures.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>lectures.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lectures.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lectures.talk_id</code>.
     */
    public void setTalkId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>lectures.talk_id</code>.
     */
    public UUID getTalkId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>lectures.speaker_id</code>.
     */
    public void setSpeakerId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>lectures.speaker_id</code>.
     */
    public Long getSpeakerId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>lectures.media_s3_key</code>.
     */
    public void setMediaS3Key(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lectures.media_s3_key</code>.
     */
    public String getMediaS3Key() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lectures.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>lectures.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LecturesRecord
     */
    public LecturesRecord() {
        super(Lectures.LECTURES);
    }

    /**
     * Create a detached, initialised LecturesRecord
     */
    public LecturesRecord(UUID id, String title, UUID talkId, Long speakerId, String mediaS3Key, LocalDateTime createdDate) {
        super(Lectures.LECTURES);

        setId(id);
        setTitle(title);
        setTalkId(talkId);
        setSpeakerId(speakerId);
        setMediaS3Key(mediaS3Key);
        setCreatedDate(createdDate);
        resetTouchedOnNotNull();
    }
}
