/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.shaxowskiy.javaspeakerclub.jooq.tables.SpeakerRoles;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpeakerRolesRecord extends UpdatableRecordImpl<SpeakerRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>speaker_roles.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>speaker_roles.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>speaker_roles.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>speaker_roles.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>speaker_roles.speaker_id</code>.
     */
    public void setSpeakerId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>speaker_roles.speaker_id</code>.
     */
    public Long getSpeakerId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>speaker_roles.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>speaker_roles.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpeakerRolesRecord
     */
    public SpeakerRolesRecord() {
        super(SpeakerRoles.SPEAKER_ROLES);
    }

    /**
     * Create a detached, initialised SpeakerRolesRecord
     */
    public SpeakerRolesRecord(Long id, String name, Long speakerId, LocalDateTime createdDate) {
        super(SpeakerRoles.SPEAKER_ROLES);

        setId(id);
        setName(name);
        setSpeakerId(speakerId);
        setCreatedDate(createdDate);
        resetTouchedOnNotNull();
    }
}
