/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.shaxowskiy.javaspeakerclub.jooq.tables.Talks;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TalksRecord extends UpdatableRecordImpl<TalksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>talks.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>talks.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>talks.speaker_id</code>.
     */
    public void setSpeakerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>talks.speaker_id</code>.
     */
    public Long getSpeakerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>talks.topic</code>.
     */
    public void setTopic(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>talks.topic</code>.
     */
    public String getTopic() {
        return (String) get(2);
    }

    /**
     * Setter for <code>talks.talk_date</code>.
     */
    public void setTalkDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>talks.talk_date</code>.
     */
    public LocalDateTime getTalkDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>talks.conference_type</code>.
     */
    public void setConferenceType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>talks.conference_type</code>.
     */
    public String getConferenceType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>talks.format</code>.
     */
    public void setFormat(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>talks.format</code>.
     */
    public String getFormat() {
        return (String) get(5);
    }

    /**
     * Setter for <code>talks.activity_name</code>.
     */
    public void setActivityName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>talks.activity_name</code>.
     */
    public String getActivityName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>talks.activity_date</code>.
     */
    public void setActivityDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>talks.activity_date</code>.
     */
    public LocalDateTime getActivityDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>talks.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>talks.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TalksRecord
     */
    public TalksRecord() {
        super(Talks.TALKS);
    }

    /**
     * Create a detached, initialised TalksRecord
     */
    public TalksRecord(UUID id, Long speakerId, String topic, LocalDateTime talkDate, String conferenceType, String format, String activityName, LocalDateTime activityDate, LocalDateTime createdDate) {
        super(Talks.TALKS);

        setId(id);
        setSpeakerId(speakerId);
        setTopic(topic);
        setTalkDate(talkDate);
        setConferenceType(conferenceType);
        setFormat(format);
        setActivityName(activityName);
        setActivityDate(activityDate);
        setCreatedDate(createdDate);
        resetTouchedOnNotNull();
    }
}
