/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import ru.shaxowskiy.javaspeakerclub.jooq.tables.UserMedia;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserMediaRecord extends UpdatableRecordImpl<UserMediaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_media.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_media.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>user_media.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_media.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>user_media.media_minio_key</code>.
     */
    public void setMediaMinioKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_media.media_minio_key</code>.
     */
    public String getMediaMinioKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_media.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_media.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserMediaRecord
     */
    public UserMediaRecord() {
        super(UserMedia.USER_MEDIA);
    }

    /**
     * Create a detached, initialised UserMediaRecord
     */
    public UserMediaRecord(UUID id, Long userId, String mediaMinioKey, LocalDateTime createdDate) {
        super(UserMedia.USER_MEDIA);

        setId(id);
        setUserId(userId);
        setMediaMinioKey(mediaMinioKey);
        setCreatedDate(createdDate);
        resetTouchedOnNotNull();
    }
}
