/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;

import ru.shaxowskiy.javaspeakerclub.jooq.tables.Lectures;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.SpeakerRoles;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Talks;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.UserMedia;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.UserRoles;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>lectures</code>.
     */
    public final Lectures LECTURES = Lectures.LECTURES;

    /**
     * The table <code>speaker_roles</code>.
     */
    public final SpeakerRoles SPEAKER_ROLES = SpeakerRoles.SPEAKER_ROLES;

    /**
     * The table <code>talks</code>.
     */
    public final Talks TALKS = Talks.TALKS;

    /**
     * The table <code>user_media</code>.
     */
    public final UserMedia USER_MEDIA = UserMedia.USER_MEDIA;

    /**
     * The table <code>user_roles</code>.
     */
    public final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super(DSL.name(""), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Lectures.LECTURES,
            SpeakerRoles.SPEAKER_ROLES,
            Talks.TALKS,
            UserMedia.USER_MEDIA,
            UserRoles.USER_ROLES,
            Users.USERS
        );
    }
}
