/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.shaxowskiy.javaspeakerclub.jooq.tables.Lectures;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.SpeakerRoles;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Talks;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.UserMedia;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.UserRoles;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_LECTURES_SPEAKER_ID = Internal.createIndex(DSL.name("idx_lectures_speaker_id"), Lectures.LECTURES, new OrderField[] { Lectures.LECTURES.SPEAKER_ID }, false);
    public static final Index IDX_LECTURES_TALK_ID = Internal.createIndex(DSL.name("idx_lectures_talk_id"), Lectures.LECTURES, new OrderField[] { Lectures.LECTURES.TALK_ID }, false);
    public static final Index IDX_SPEAKER_ROLES_NAME = Internal.createIndex(DSL.name("idx_speaker_roles_name"), SpeakerRoles.SPEAKER_ROLES, new OrderField[] { SpeakerRoles.SPEAKER_ROLES.NAME }, false);
    public static final Index IDX_SPEAKER_ROLES_SPEAKER_ID = Internal.createIndex(DSL.name("idx_speaker_roles_speaker_id"), SpeakerRoles.SPEAKER_ROLES, new OrderField[] { SpeakerRoles.SPEAKER_ROLES.SPEAKER_ID }, false);
    public static final Index IDX_TALKS_SPEAKER_ID = Internal.createIndex(DSL.name("idx_talks_speaker_id"), Talks.TALKS, new OrderField[] { Talks.TALKS.SPEAKER_ID }, false);
    public static final Index IDX_USER_MEDIA_USER_ID = Internal.createIndex(DSL.name("idx_user_media_user_id"), UserMedia.USER_MEDIA, new OrderField[] { UserMedia.USER_MEDIA.USER_ID }, false);
    public static final Index IDX_USER_ROLES_USER_ID = Internal.createIndex(DSL.name("idx_user_roles_user_id"), UserRoles.USER_ROLES, new OrderField[] { UserRoles.USER_ROLES.USER_ID }, false);
}
