/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;

import ru.shaxowskiy.javaspeakerclub.jooq.tables.Lectures;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.SpeakerRoles;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Talks;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.UserMedia;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.UserRoles;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Users;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.LecturesRecord;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.SpeakerRolesRecord;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.TalksRecord;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.UserMediaRecord;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.UserRolesRecord;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LecturesRecord> CONSTRAINT_61 = Internal.createUniqueKey(Lectures.LECTURES, DSL.name("CONSTRAINT_61"), new TableField[] { Lectures.LECTURES.ID }, true);
    public static final UniqueKey<SpeakerRolesRecord> CONSTRAINT_F = Internal.createUniqueKey(SpeakerRoles.SPEAKER_ROLES, DSL.name("CONSTRAINT_F"), new TableField[] { SpeakerRoles.SPEAKER_ROLES.ID }, true);
    public static final UniqueKey<TalksRecord> CONSTRAINT_69 = Internal.createUniqueKey(Talks.TALKS, DSL.name("CONSTRAINT_69"), new TableField[] { Talks.TALKS.ID }, true);
    public static final UniqueKey<UserMediaRecord> CONSTRAINT_72 = Internal.createUniqueKey(UserMedia.USER_MEDIA, DSL.name("CONSTRAINT_72"), new TableField[] { UserMedia.USER_MEDIA.ID }, true);
    public static final UniqueKey<UserMediaRecord> CONSTRAINT_72F = Internal.createUniqueKey(UserMedia.USER_MEDIA, DSL.name("CONSTRAINT_72F"), new TableField[] { UserMedia.USER_MEDIA.MEDIA_MINIO_KEY }, true);
    public static final UniqueKey<UserRolesRecord> CONSTRAINT_7 = Internal.createUniqueKey(UserRoles.USER_ROLES, DSL.name("CONSTRAINT_7"), new TableField[] { UserRoles.USER_ROLES.ID }, true);
    public static final UniqueKey<UserRolesRecord> UQ_USER_ROLES_USER_ROLE = Internal.createUniqueKey(UserRoles.USER_ROLES, DSL.name("uq_user_roles_user_role"), new TableField[] { UserRoles.USER_ROLES.USER_ID, UserRoles.USER_ROLES.ROLE }, true);
    public static final UniqueKey<UsersRecord> CONSTRAINT_6 = Internal.createUniqueKey(Users.USERS, DSL.name("CONSTRAINT_6"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> CONSTRAINT_6A = Internal.createUniqueKey(Users.USERS, DSL.name("CONSTRAINT_6A"), new TableField[] { Users.USERS.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LecturesRecord, TalksRecord> FK_LECTURES_TALKS_TALK_ID = Internal.createForeignKey(Lectures.LECTURES, DSL.name("fk_lectures_talks_talk_id"), new TableField[] { Lectures.LECTURES.TALK_ID }, Keys.CONSTRAINT_69, new TableField[] { Talks.TALKS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.RESTRICT);
    public static final ForeignKey<LecturesRecord, UsersRecord> FK_LECTURES_USERS_SPEAKER_ID = Internal.createForeignKey(Lectures.LECTURES, DSL.name("fk_lectures_users_speaker_id"), new TableField[] { Lectures.LECTURES.SPEAKER_ID }, Keys.CONSTRAINT_6, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.RESTRICT);
    public static final ForeignKey<SpeakerRolesRecord, UsersRecord> FK_SPEAKER_ROLES_USERS_SPEAKER_ID = Internal.createForeignKey(SpeakerRoles.SPEAKER_ROLES, DSL.name("fk_speaker_roles_users_speaker_id"), new TableField[] { SpeakerRoles.SPEAKER_ROLES.SPEAKER_ID }, Keys.CONSTRAINT_6, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.RESTRICT);
    public static final ForeignKey<TalksRecord, UsersRecord> FK_TALKS_USERS_SPEAKER_ID = Internal.createForeignKey(Talks.TALKS, DSL.name("fk_talks_users_speaker_id"), new TableField[] { Talks.TALKS.SPEAKER_ID }, Keys.CONSTRAINT_6, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.RESTRICT);
    public static final ForeignKey<UserMediaRecord, UsersRecord> FK_USER_MEDIA_USERS_USER_ID = Internal.createForeignKey(UserMedia.USER_MEDIA, DSL.name("fk_user_media_users_user_id"), new TableField[] { UserMedia.USER_MEDIA.USER_ID }, Keys.CONSTRAINT_6, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.RESTRICT);
    public static final ForeignKey<UserRolesRecord, UsersRecord> FK_USER_ROLES_USERS_USER_ID = Internal.createForeignKey(UserRoles.USER_ROLES, DSL.name("fk_user_roles_users_user_id"), new TableField[] { UserRoles.USER_ROLES.USER_ID }, Keys.CONSTRAINT_6, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.RESTRICT);
}
