/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq;


import ru.shaxowskiy.javaspeakerclub.jooq.tables.Lectures;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.SpeakerRoles;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Talks;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.UserMedia;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.UserRoles;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>lectures</code>.
     */
    public static final Lectures LECTURES = Lectures.LECTURES;

    /**
     * The table <code>speaker_roles</code>.
     */
    public static final SpeakerRoles SPEAKER_ROLES = SpeakerRoles.SPEAKER_ROLES;

    /**
     * The table <code>talks</code>.
     */
    public static final Talks TALKS = Talks.TALKS;

    /**
     * The table <code>user_media</code>.
     */
    public static final UserMedia USER_MEDIA = UserMedia.USER_MEDIA;

    /**
     * The table <code>user_roles</code>.
     */
    public static final UserRoles USER_ROLES = UserRoles.USER_ROLES;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
