/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.shaxowskiy.javaspeakerclub.jooq.DefaultSchema;
import ru.shaxowskiy.javaspeakerclub.jooq.Indexes;
import ru.shaxowskiy.javaspeakerclub.jooq.Keys;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Talks.TalksPath;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Users.UsersPath;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.LecturesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lectures extends TableImpl<LecturesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lectures</code>
     */
    public static final Lectures LECTURES = new Lectures();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LecturesRecord> getRecordType() {
        return LecturesRecord.class;
    }

    /**
     * The column <code>lectures.id</code>.
     */
    public final TableField<LecturesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>lectures.title</code>.
     */
    public final TableField<LecturesRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>lectures.talk_id</code>.
     */
    public final TableField<LecturesRecord, UUID> TALK_ID = createField(DSL.name("talk_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>lectures.speaker_id</code>.
     */
    public final TableField<LecturesRecord, Long> SPEAKER_ID = createField(DSL.name("speaker_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>lectures.media_s3_key</code>.
     */
    public final TableField<LecturesRecord, String> MEDIA_S3_KEY = createField(DSL.name("media_s3_key"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>lectures.created_date</code>.
     */
    public final TableField<LecturesRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Lectures(Name alias, Table<LecturesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lectures(Name alias, Table<LecturesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>lectures</code> table reference
     */
    public Lectures(String alias) {
        this(DSL.name(alias), LECTURES);
    }

    /**
     * Create an aliased <code>lectures</code> table reference
     */
    public Lectures(Name alias) {
        this(alias, LECTURES);
    }

    /**
     * Create a <code>lectures</code> table reference
     */
    public Lectures() {
        this(DSL.name("lectures"), null);
    }

    public <O extends Record> Lectures(Table<O> path, ForeignKey<O, LecturesRecord> childPath, InverseForeignKey<O, LecturesRecord> parentPath) {
        super(path, childPath, parentPath, LECTURES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LecturesPath extends Lectures implements Path<LecturesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> LecturesPath(Table<O> path, ForeignKey<O, LecturesRecord> childPath, InverseForeignKey<O, LecturesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LecturesPath(Name alias, Table<LecturesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LecturesPath as(String alias) {
            return new LecturesPath(DSL.name(alias), this);
        }

        @Override
        public LecturesPath as(Name alias) {
            return new LecturesPath(alias, this);
        }

        @Override
        public LecturesPath as(Table<?> alias) {
            return new LecturesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_LECTURES_SPEAKER_ID, Indexes.IDX_LECTURES_TALK_ID);
    }

    @Override
    public UniqueKey<LecturesRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_61;
    }

    @Override
    public List<ForeignKey<LecturesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_LECTURES_TALKS_TALK_ID, Keys.FK_LECTURES_USERS_SPEAKER_ID);
    }

    private transient TalksPath _talks;

    /**
     * Get the implicit join path to the <code>talks</code> table.
     */
    public TalksPath talks() {
        if (_talks == null)
            _talks = new TalksPath(this, Keys.FK_LECTURES_TALKS_TALK_ID, null);

        return _talks;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_LECTURES_USERS_SPEAKER_ID, null);

        return _users;
    }

    @Override
    public Lectures as(String alias) {
        return new Lectures(DSL.name(alias), this);
    }

    @Override
    public Lectures as(Name alias) {
        return new Lectures(alias, this);
    }

    @Override
    public Lectures as(Table<?> alias) {
        return new Lectures(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lectures rename(String name) {
        return new Lectures(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lectures rename(Name name) {
        return new Lectures(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lectures rename(Table<?> name) {
        return new Lectures(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lectures where(Condition condition) {
        return new Lectures(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lectures where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lectures where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lectures where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lectures where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lectures where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lectures where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lectures where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lectures whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lectures whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
