/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.shaxowskiy.javaspeakerclub.jooq.DefaultSchema;
import ru.shaxowskiy.javaspeakerclub.jooq.Indexes;
import ru.shaxowskiy.javaspeakerclub.jooq.Keys;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Users.UsersPath;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.SpeakerRolesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpeakerRoles extends TableImpl<SpeakerRolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>speaker_roles</code>
     */
    public static final SpeakerRoles SPEAKER_ROLES = new SpeakerRoles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpeakerRolesRecord> getRecordType() {
        return SpeakerRolesRecord.class;
    }

    /**
     * The column <code>speaker_roles.id</code>.
     */
    public final TableField<SpeakerRolesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>speaker_roles.name</code>.
     */
    public final TableField<SpeakerRolesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>speaker_roles.speaker_id</code>.
     */
    public final TableField<SpeakerRolesRecord, Long> SPEAKER_ID = createField(DSL.name("speaker_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>speaker_roles.created_date</code>.
     */
    public final TableField<SpeakerRolesRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private SpeakerRoles(Name alias, Table<SpeakerRolesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SpeakerRoles(Name alias, Table<SpeakerRolesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>speaker_roles</code> table reference
     */
    public SpeakerRoles(String alias) {
        this(DSL.name(alias), SPEAKER_ROLES);
    }

    /**
     * Create an aliased <code>speaker_roles</code> table reference
     */
    public SpeakerRoles(Name alias) {
        this(alias, SPEAKER_ROLES);
    }

    /**
     * Create a <code>speaker_roles</code> table reference
     */
    public SpeakerRoles() {
        this(DSL.name("speaker_roles"), null);
    }

    public <O extends Record> SpeakerRoles(Table<O> path, ForeignKey<O, SpeakerRolesRecord> childPath, InverseForeignKey<O, SpeakerRolesRecord> parentPath) {
        super(path, childPath, parentPath, SPEAKER_ROLES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SpeakerRolesPath extends SpeakerRoles implements Path<SpeakerRolesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SpeakerRolesPath(Table<O> path, ForeignKey<O, SpeakerRolesRecord> childPath, InverseForeignKey<O, SpeakerRolesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SpeakerRolesPath(Name alias, Table<SpeakerRolesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SpeakerRolesPath as(String alias) {
            return new SpeakerRolesPath(DSL.name(alias), this);
        }

        @Override
        public SpeakerRolesPath as(Name alias) {
            return new SpeakerRolesPath(alias, this);
        }

        @Override
        public SpeakerRolesPath as(Table<?> alias) {
            return new SpeakerRolesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SPEAKER_ROLES_NAME, Indexes.IDX_SPEAKER_ROLES_SPEAKER_ID);
    }

    @Override
    public Identity<SpeakerRolesRecord, Long> getIdentity() {
        return (Identity<SpeakerRolesRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SpeakerRolesRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_F;
    }

    @Override
    public List<ForeignKey<SpeakerRolesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SPEAKER_ROLES_USERS_SPEAKER_ID);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_SPEAKER_ROLES_USERS_SPEAKER_ID, null);

        return _users;
    }

    @Override
    public SpeakerRoles as(String alias) {
        return new SpeakerRoles(DSL.name(alias), this);
    }

    @Override
    public SpeakerRoles as(Name alias) {
        return new SpeakerRoles(alias, this);
    }

    @Override
    public SpeakerRoles as(Table<?> alias) {
        return new SpeakerRoles(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpeakerRoles rename(String name) {
        return new SpeakerRoles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpeakerRoles rename(Name name) {
        return new SpeakerRoles(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpeakerRoles rename(Table<?> name) {
        return new SpeakerRoles(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpeakerRoles where(Condition condition) {
        return new SpeakerRoles(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpeakerRoles where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpeakerRoles where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpeakerRoles where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpeakerRoles where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpeakerRoles where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpeakerRoles where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpeakerRoles where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpeakerRoles whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpeakerRoles whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
