/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.shaxowskiy.javaspeakerclub.jooq.DefaultSchema;
import ru.shaxowskiy.javaspeakerclub.jooq.Indexes;
import ru.shaxowskiy.javaspeakerclub.jooq.Keys;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Lectures.LecturesPath;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Users.UsersPath;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.TalksRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Talks extends TableImpl<TalksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>talks</code>
     */
    public static final Talks TALKS = new Talks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TalksRecord> getRecordType() {
        return TalksRecord.class;
    }

    /**
     * The column <code>talks.id</code>.
     */
    public final TableField<TalksRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>talks.speaker_id</code>.
     */
    public final TableField<TalksRecord, Long> SPEAKER_ID = createField(DSL.name("speaker_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>talks.topic</code>.
     */
    public final TableField<TalksRecord, String> TOPIC = createField(DSL.name("topic"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>talks.talk_date</code>.
     */
    public final TableField<TalksRecord, LocalDateTime> TALK_DATE = createField(DSL.name("talk_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>talks.conference_type</code>.
     */
    public final TableField<TalksRecord, String> CONFERENCE_TYPE = createField(DSL.name("conference_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>talks.format</code>.
     */
    public final TableField<TalksRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>talks.activity_name</code>.
     */
    public final TableField<TalksRecord, String> ACTIVITY_NAME = createField(DSL.name("activity_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>talks.activity_date</code>.
     */
    public final TableField<TalksRecord, LocalDateTime> ACTIVITY_DATE = createField(DSL.name("activity_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>talks.created_date</code>.
     */
    public final TableField<TalksRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Talks(Name alias, Table<TalksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Talks(Name alias, Table<TalksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>talks</code> table reference
     */
    public Talks(String alias) {
        this(DSL.name(alias), TALKS);
    }

    /**
     * Create an aliased <code>talks</code> table reference
     */
    public Talks(Name alias) {
        this(alias, TALKS);
    }

    /**
     * Create a <code>talks</code> table reference
     */
    public Talks() {
        this(DSL.name("talks"), null);
    }

    public <O extends Record> Talks(Table<O> path, ForeignKey<O, TalksRecord> childPath, InverseForeignKey<O, TalksRecord> parentPath) {
        super(path, childPath, parentPath, TALKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TalksPath extends Talks implements Path<TalksRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TalksPath(Table<O> path, ForeignKey<O, TalksRecord> childPath, InverseForeignKey<O, TalksRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TalksPath(Name alias, Table<TalksRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TalksPath as(String alias) {
            return new TalksPath(DSL.name(alias), this);
        }

        @Override
        public TalksPath as(Name alias) {
            return new TalksPath(alias, this);
        }

        @Override
        public TalksPath as(Table<?> alias) {
            return new TalksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TALKS_SPEAKER_ID);
    }

    @Override
    public UniqueKey<TalksRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_69;
    }

    @Override
    public List<ForeignKey<TalksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_TALKS_USERS_SPEAKER_ID);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_TALKS_USERS_SPEAKER_ID, null);

        return _users;
    }

    private transient LecturesPath _lectures;

    /**
     * Get the implicit to-many join path to the <code>lectures</code> table
     */
    public LecturesPath lectures() {
        if (_lectures == null)
            _lectures = new LecturesPath(this, null, Keys.FK_LECTURES_TALKS_TALK_ID.getInverseKey());

        return _lectures;
    }

    @Override
    public Talks as(String alias) {
        return new Talks(DSL.name(alias), this);
    }

    @Override
    public Talks as(Name alias) {
        return new Talks(alias, this);
    }

    @Override
    public Talks as(Table<?> alias) {
        return new Talks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Talks rename(String name) {
        return new Talks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Talks rename(Name name) {
        return new Talks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Talks rename(Table<?> name) {
        return new Talks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Talks where(Condition condition) {
        return new Talks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Talks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Talks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Talks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Talks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Talks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Talks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Talks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Talks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Talks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
