/*
 * This file is generated by jOOQ.
 */
package ru.shaxowskiy.javaspeakerclub.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.shaxowskiy.javaspeakerclub.jooq.DefaultSchema;
import ru.shaxowskiy.javaspeakerclub.jooq.Indexes;
import ru.shaxowskiy.javaspeakerclub.jooq.Keys;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.Users.UsersPath;
import ru.shaxowskiy.javaspeakerclub.jooq.tables.records.UserMediaRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserMedia extends TableImpl<UserMediaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user_media</code>
     */
    public static final UserMedia USER_MEDIA = new UserMedia();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserMediaRecord> getRecordType() {
        return UserMediaRecord.class;
    }

    /**
     * The column <code>user_media.id</code>.
     */
    public final TableField<UserMediaRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>user_media.user_id</code>.
     */
    public final TableField<UserMediaRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>user_media.media_minio_key</code>.
     */
    public final TableField<UserMediaRecord, String> MEDIA_MINIO_KEY = createField(DSL.name("media_minio_key"), SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>user_media.created_date</code>.
     */
    public final TableField<UserMediaRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private UserMedia(Name alias, Table<UserMediaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserMedia(Name alias, Table<UserMediaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>user_media</code> table reference
     */
    public UserMedia(String alias) {
        this(DSL.name(alias), USER_MEDIA);
    }

    /**
     * Create an aliased <code>user_media</code> table reference
     */
    public UserMedia(Name alias) {
        this(alias, USER_MEDIA);
    }

    /**
     * Create a <code>user_media</code> table reference
     */
    public UserMedia() {
        this(DSL.name("user_media"), null);
    }

    public <O extends Record> UserMedia(Table<O> path, ForeignKey<O, UserMediaRecord> childPath, InverseForeignKey<O, UserMediaRecord> parentPath) {
        super(path, childPath, parentPath, USER_MEDIA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserMediaPath extends UserMedia implements Path<UserMediaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserMediaPath(Table<O> path, ForeignKey<O, UserMediaRecord> childPath, InverseForeignKey<O, UserMediaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserMediaPath(Name alias, Table<UserMediaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserMediaPath as(String alias) {
            return new UserMediaPath(DSL.name(alias), this);
        }

        @Override
        public UserMediaPath as(Name alias) {
            return new UserMediaPath(alias, this);
        }

        @Override
        public UserMediaPath as(Table<?> alias) {
            return new UserMediaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_MEDIA_USER_ID);
    }

    @Override
    public UniqueKey<UserMediaRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_72;
    }

    @Override
    public List<UniqueKey<UserMediaRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_72F);
    }

    @Override
    public List<ForeignKey<UserMediaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_USER_MEDIA_USERS_USER_ID);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.FK_USER_MEDIA_USERS_USER_ID, null);

        return _users;
    }

    @Override
    public UserMedia as(String alias) {
        return new UserMedia(DSL.name(alias), this);
    }

    @Override
    public UserMedia as(Name alias) {
        return new UserMedia(alias, this);
    }

    @Override
    public UserMedia as(Table<?> alias) {
        return new UserMedia(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMedia rename(String name) {
        return new UserMedia(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMedia rename(Name name) {
        return new UserMedia(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserMedia rename(Table<?> name) {
        return new UserMedia(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMedia where(Condition condition) {
        return new UserMedia(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMedia where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMedia where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMedia where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMedia where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMedia where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMedia where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserMedia where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMedia whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserMedia whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
